apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sliks.ahmedtremo.com
spec:
  group: ahmedtremo.com
  versions:
    - additionalPrinterColumns:
      - jsonPath: .status.state
        name: State
        type: string
      - jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
      name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                slurmdbd:
                  type: boolean
                  default: false
                slurmrestd:
                  type: boolean
                  default: false
                mariadb:
                  type: object
                  default: {}
                  properties:
                    storage_size:
                      type: string
                      default: 5G
                      pattern: ^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$
                    storage_class:
                      type: string
                      default: default
              required:
                - namespace
                - slurmdbd
                - slurmrestd
            status:
              type: object
              properties:
                state:
                  type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: sliks
    singular: slik
    kind: Slik
    shortNames:
    - slik