name: Checks

on:
  push:
  pull_request:

jobs:
  Golangci-Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Install dependencies
        run: |
          go version
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.1

      - name: Run golangci-lint
        run: |
          golangci-lint run cmd/...
          golangci-lint run spec/...
